#
# Docker file for Tilix CI tests on Debian Testing
#
FROM debian:testing

# prepare
RUN mkdir -p /build/ci/

# install build dependencies
COPY install-deps-deb.sh /build/ci/
RUN chmod +x /build/ci/install-deps-deb.sh && /build/ci/install-deps-deb.sh

# install GtkD directly from the source repos, we don't need to build it again
RUN eatmydata apt-get install -yq libgtkd-3-dev libvted-3-dev

# finish
WORKDIR /build
